### ISSUE TITLE
RESAIL: run in latest compiler

### ISSUE THREAD

**Issue by rfchang** [ThePuriProdigy/cram#3]
@jafingerhut: run RESAIL in latest compiler version to see if the weird stage allocation is persistent

**Comment by jafingerhut** [comment]
One of the compiler engineers, Glen Gibb, is looking into the reasons why the installation of the latest Tofino SDE was failing for me today.  Hopefully he can find a fix soon.

**Comment by jafingerhut** [comment]
Recompiled with SDE 9.13.1, and all umd_bitstring_<j> != 0 comparisons now seem to be performed in a single stage.  Woohoo!

**Comment by jafingerhut** [comment]
Well, not all, but many more than 3 of them.  A few are done earlier, and maybe one is done later.  But much nicer than before.

**Comment by rfchang** [comment]
Sounds great. Closing this issue as RESAIL is about done.
